### PR TITLE
[WIP] Various minor stuff

### LINKED ISSUE #15: Handle indices that appear on lhs but not rhs better
This

``` julia
@einsum A[i,j] := B[i]
```

Throws an error that could be better explained (though it isn't terrible):

```
ERROR: UndefVarError: A not defined
 in macro expansion; at /Users/alex/.julia/v0.5/Einsum/src/Einsum.jl:127 [inlined]
 in anonymous at ./<missing>:?
```

### PR DESCRIPTION
**Pull request by phipsgabler**
To review for anyone working on the project (@mcabbott?):

- A lot of renamings of variables, to something which I believe to be more clear and consistent
- Move dimension checks and type definitions outside the `let` around the loops -- this allows to reuse the output type `gensym(T)` to be used throughout, instead of repeating the promotion
- Add some documentation to `extract_indices` and `nest_loops`
- Add `check_index_occurrence`, which should fix #15

### CODE REVIEW

File: src/Einsum.jl [hunk 1]
```diff
@@ -27,336 +28,404 @@ macro einsum_checkinbounds(ex)
     _einsum(ex, false) # false, false
 end
 
-function _einsum(ex::Expr, inbounds = true, simd = false, threads=false)
+
+function _einsum(expr::Expr, inbounds = true, simd = false, threads = false)
```
Comment (mcabbott) [inline src/Einsum.jl:32]: If changing this, can we make it different to the output expression? `input_expr` or something.

File: src/Einsum.jl [hunk 2]
```diff
@@ -27,336 +28,404 @@ macro einsum_checkinbounds(ex)
...
     elseif simd
-      loop = :(@simd $loop)
+        loop = :(@simd $loop)
     end
 
     return quote
-        local $ix
+        local $index_name
         $loop
     end
```
Comment (mcabbott) [inline src/Einsum.jl:287]: I'm pretty sure we can just `return loop` here -- the for loop automatically makes its index local.

File: test/runtests.jl [hunk 3]
```diff
@@ -7,296 +6,296 @@ using Einsum
...
-  @einsum x[i] := y[i]
-  @test i == -1
+    i = -1
+    y = randn(10)
+    @einsum x[i] := y[i]
+    @test i == -1
 end
 
 ## Test that B is overwritten by := operator
 let
```
Comment (mcabbott) [inline test/runtests.jl:16]: If energetic it might be nice to replace all these let blocks with things like
```julia
@testset "Test that B is overwritten by := operator" begin
...
end
```

File: src/Einsum.jl [hunk 4]
```diff
@@ -27,336 +28,404 @@ macro einsum_checkinbounds(ex)
...
-    push!(idx_store, ex)
-    push!(dim_store, :(size($arrname, $position)))
-    return idx_store, arr_store, dim_store
+function extractindex!(expr::Symbol, array_name::Symbol, dimension::Int,
+                       array_names::Vector{Symbol},
+                       index_names::Vector{Symbol},
+                       axis_expressions::Vector{Expr})
+    push!(index_names, expr)
+    push!(axis_expressions, :(size($array_name, $dimension)))
+    return array_names, index_names, axis_expressions
```
Comment (mcabbott) [inline src/Einsum.jl]: The return value of `extractindex!` (singular) isn't used, perhaps clearer to remove it: 
```suggestion
    return nothing
```

File: src/Einsum.jl [hunk 5]
```diff
@@ -27,336 +28,404 @@ macro einsum_checkinbounds(ex)
...
 end
 
-function extractindex!(ex::Number, arrname, position,
-                       idx_store, arr_store, dim_store)
-    return idx_store, arr_store, dim_store
+function extractindex!(expr::Number, array_name::Symbol, dimension::Int,
+                       array_names::Vector{Symbol},
+                       index_names::Vector{Symbol},
+                       axis_expressions::Vector{Expr})
+    return array_names, index_names, axis_expressions
```
Comment (mcabbott) [inline src/Einsum.jl]:
```suggestion
    return nothing
```

File: src/Einsum.jl [hunk 6]
```diff
@@ -27,336 +28,404 @@ macro einsum_checkinbounds(ex)
...
-    elseif Meta.isexpr(ex, :quote)
+    elseif Meta.isexpr(expr, :quote)
         # nothing
     else
-        throw(ArgumentError("Invalid index expression: `$(ex)`"))
+        throw(ArgumentError("Invalid index expression: `$(expr)`"))
     end
 
-    return idx_store, arr_store, dim_store
+    return array_names, index_names, axis_expressions
```
Comment (mcabbott) [inline src/Einsum.jl]:
```suggestion
    return nothing
```

File: src/Einsum.jl [hunk 7]
```diff
@@ -27,336 +28,404 @@ macro einsum_checkinbounds(ex)
...
     else
-        throw(ArgumentError("Invalid expression head: `:$(ex.head)`"))
+        throw(ArgumentError("Invalid expression head: `:$(expr.head)`"))
     end
 
-    return idx_store, arr_store, dim_store
+    return return array_names, index_names, axis_expressions
 end
 
-function extractindex!(ex::Symbol, arrname, position,
```
Comment (mcabbott) [inline src/Einsum.jl:287]: I'd be tempted to leave most arguments of `extractindex!` without types, to be clearer that only `ex::Symbol` etc. varies between the methods. 

I'd also perhaps rename `extractindex!` -> `extract_one!` or something more obviously different.

File: src/Einsum.jl [hunk 8]
```diff
@@ -27,336 +28,404 @@ macro einsum_checkinbounds(ex)
...
-                         idx_store::Vector{Symbol},
-                         arr_store::Vector{Symbol},
-                         dim_store::Vector{Expr})
-    return idx_store, arr_store, dim_store
+function extractindices!(expr::Number,
+                         array_names::Vector{Symbol},
+                         index_names::Vector{Symbol},
+                         axis_expressions::Vector{Expr})
+    return array_names, index_names, axis_expressions
 end
```
Comment (mcabbott) [inline src/Einsum.jl:320]:
```suggestion
```

File: src/Einsum.jl [hunk 9]
```diff
@@ -27,336 +28,404 @@ macro einsum_checkinbounds(ex)
...
-                         idx_store::Vector{Symbol},
-                         arr_store::Vector{Symbol},
-                         dim_store::Vector{Expr})
-    push!(arr_store, ex)
-    return idx_store, arr_store, dim_store
+function extractindices!(expr::Symbol,
+                         array_names::Vector{Symbol},
+                         index_names::Vector{Symbol},
+                         axis_expressions::Vector{Expr})
+    push!(array_names, expr)
```
Comment (mcabbott) [inline src/Einsum.jl:310]:
```suggestion
    push!(array_names, expr)
    
```

**Review by mcabbott — COMMENTED** [review]
OK I added some comments, perhaps too many... but agree with making it tidier!

File: src/Einsum.jl [hunk 10]
```diff
@@ -27,336 +28,404 @@ macro einsum_checkinbounds(ex)
...
-        ex = :(@inbounds $ex)
+        expr = :(@inbounds $expr)
     end
 
     full_expression = quote
-        $ex_create_arrays
+        $type_definition
+        $output_definition
+        $(dimension_checks...)
         let
```
Comment (mcabbott) [inline src/Einsum.jl]: One more thought. Does this let block do anything? `quote` already wraps in `begin end` thus local T shouldn't escape. Ah I see T is outside it now anyway... so it wraps only for loops, even less likely to do anything.

**Comment by phipsgabler** [comment]
Thanks for the suggestions!

About the `let` and the `local ix` things: I think your right.  To be honest, I just left these constructions untouched over all my refactorings, fearing that something unexpected _might_ happen without them.  But I'll try to remove them and see what happens.

File: test/runtests.jl (hunk 3 above)
Comment (phipsgabler) [reply test/runtests.jl:16]: That's definitely a good idea.

**Comment by mcabbott** [comment]
I did the same thing... but judging by the red X, it looks like I've forgotten what the scoping rules were last year. This is what 0.7 says: 
```
┌ Warning: Use of final value of loop variable `i` around /home/travis/build/ahwillia/Einsum.jl/test/runtests.jl:12 is deprecated. In the future the variable will be local to the loop instead.
└ @ ~/build/ahwillia/Einsum.jl/test/runtests.jl:12
Test Failed at /home/travis/build/ahwillia/Einsum.jl/test/runtests.jl:12
  Expression: i == -1
   Evaluated: 10 == -1
```
Perhaps what stays should just get a `# remove when we drop 0.6 support`. But surely one only needs one barrier, not one on every loop, all the loop indices are generated.

**Comment by phipsgabler** [comment]
Loop variable having non-local scope are a bit unexpected, indeed... I changed it to one `let` around the loops, so `@einsum A[i] = B[i]` becomes

```julia
let i
    for i = 1:size(A, 1)
        A[i] = B[i]
    end 
end
```

Do you think that's fine?  The checks pass on all versions.

**Comment by mcabbott** [comment]
Sounds good, I think.
